---
- hosts: receiver
  become: true
  tasks:
    - name: sync time
      shell: "chronyc makestep"

    - name: start receive
      shell: "tmreceive -i {{ eth_ip }} -effective {{ effective }} -limit {{ limit }}"
      register: shell_result

    - name: output receive result
      debug:
        var: shell_result.stdout_lines
