---
- hosts: aws
  become: true

  tasks:
    - name: adjust upd socket buffer
      shell: "{{ item }}"
      loop:
        - "sysctl -w net.core.rmem_default=31457280"
        - "sysctl -w net.core.rmem_max=33554432"
        - "sysctl -w net.core.wmem_default=31457280"
        - "sysctl -w net.core.wmem_max=33554432"
        - "sysctl -w net.core.somaxconn=65535"
        - "sysctl -w net.core.netdev_max_backlog=65536"
        - "sysctl -w net.ipv4.udp_mem=65536131072262144"
        - "sysctl -p"

    - name: copy tmreceive & tsend
      get_url:
        url: "http://proceedwell.com/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        mode: "777"
      loop:
        - tmreceive
        - tmsend
        - msend
        - mreceive
        - supernode
        - edge

- hosts: master
  become: true

  tasks:
    - name: start n2n master
      shell: "supernode -l 1200"
      async: 2592000
      poll: 0
- hosts: sender
  become: true

  tasks:
    - name: start n2n edge
      shell: "sudo edge -l {{ n2n_master }}:1200 -c Buckhill -a {{ eth_ip }} -E"

- hosts: receiver
  become: true

  tasks:
    - name: start n2n edge
      shell: "sudo edge -l {{ n2n_master }}:1200 -c Buckhill -a {{ eth_ip }} -E"
