---
- hosts: aws_server
  become: true

  tasks:
    - name: Template openvpn server setting
      template:
        src: templates/bridge_start.sh
        dest: /opt/bridge_start.sh
        mode: "777"

    - name: run bridge start
      shell: "/opt/bridge_start.sh"
