---
- hosts: aws_client
  become: true

  tasks:
    - name: killall openvpn
      shell: "killall openvpn"

    - set_fact:
        vpnport: 1200

    - name: Template openvpn client setting
      template:
        src: templates/openvpn_bridge_client.j2
        dest: /home/ec2-user/client.ovpn
        mode: "777"

    - name: run client
      shell: "nohup openvpn client.ovpn &"

    - pause:
        seconds: 15
    - debug: var=ansible_all_ipv4_addresses
