---
- hosts: aws
  become: true

  tasks:
    - name: adjust upd socket buffer
      shell: "{{ item }}"
      loop:
        - "sysctl -w net.core.rmem_default=31457280"
        - "sysctl -w net.core.rmem_max=33554432"
        - "sysctl -w net.core.wmem_default=31457280"
        - "sysctl -w net.core.wmem_max=33554432"
        - "sysctl -w net.core.somaxconn=65535"
        - "sysctl -w net.core.netdev_max_backlog=65536"
        - "sysctl -w net.ipv4.udp_mem=65536131072262144"
        - "sysctl -p"

    - name: copy tmreceive & tsend
      get_url:
        url: "http://proceedwell.com/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        mode: "777"
      loop:
        - tmreceive
        - tmsend
        - msend
        - mreceive

    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: install rpms
      yum:
        name:
          - openvpn
          - zip
          - unzip
          - ntpdate
          - vim
          - psmisc
          - bridge-utils
        state: present
    - name: Enable password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: PasswordAuthentication yes
      

    - name: copy files
      get_url:
        url: http://proceedwell.com/{{ item.name}}
        dest: /etc/openvpn/{{ item.name}}
        mode: "644"
      loop:
        - { name: "ca.crt" }
        - { name: "dh2048.pem" }
        - { name: "server.conf" }
        - { name: "server.crt" }
        - { name: "server.key" }

    - name: copy pam
      get_url:
        url: http://proceedwell.com/{{ item.name}}
        dest: /etc/pam.d/{{ item.name}}
        mode: "644"
      loop:
        - { name: "openvpn" }

    - name: Ensure ipforward
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "^net.ipv4.ip_forward"
        line: net.ipv4.ip_forward=1

    - name: enable sysctl
      shell: "sysctl -p"

    - name: Creates openvpnclient directory
      file:
        path: /root/openvpnclient
        state: directory

  

    # - name: copy
    #   get_url:
    #     url: http://proceedwell.com/opvclient.zip
    #     dest: /root/openvpnclient/opvclient.zip
    #     mode: "777"

    - name: copy client file
      get_url:
        url: http://proceedwell.com/{{ item.name }}
        dest: /root/openvpnclient/{{ item.name }}
      loop:
        # - { name: "client.ovpn" }
        - { name: "login.conf" }
        - { name: "ca.crt" }
        - { name: "opvclient.crt" }
        - { name: "opvclient.csr" }
        - { name: "opvclient.key" }

    - name: Template openvpn client setting
      template:
        src: templates/openvpn_client.j2
        dest: /root/openvpnclient/client.ovpn
        mode: "777"
    # - name: unzip
    #   shell: "cd /root/openvpnclient && unzip opvclient.zip"
    # - name: Template client setting
    #   template:
    #     src: templates/openvpn_client.j2
    #     dest: /root/openvpnclient/client.ovpn
    #     mode: "777"

    
