---
- hosts: aws
  become: true

  tasks:
    - name: Template openvpn client setting
      template:
        src: templates/openvpn_client.j2
        dest: /home/ec2-user/client.ovpn
        mode: "777"

    - name: run client
      shell: "nohup openvpn client.ovpn &"
