---
- hosts: aws
  become: true

  tasks:
    - name: install packages
      yum:
        name:
          - psmisc
          - https://s3-ap-southeast-1.amazonaws.com/proceedwell.com/openvswitch-2.8.2-1.el7.x86_64.rpm
        state: present

    - name: adjust upd socket buffer
      shell: "sysctl -w net.core.rmem_max=500000000"

    - name: copy tmreceive & tsend
      get_url:
        url: "http://proceedwell.com/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        mode: "777"
      loop:
        - tmreceive
        - tmsend
        - msend
        - mreceive

    - name: Template  ovs script
      template:
        src: templates/ovs.j2
        dest: /tmp/ovs.sh
        mode: "777"
    - name: shell run
      shell: "/tmp/ovs.sh"

    - name: setup local ip
      shell: "ifconfig br1 {{ eth_ip }}/16 up"

    - name: connect to master
      shell: "ovs-vsctl add-port br1 vx1 -- set interface vx1 type=vxlan options:remote_ip=172.31.19.231"
