---
- hosts: aws
  become: true

  tasks:
    - name: upgrade all packages, excluding kernel & foo related packages
      yum:
        name: "*"
        state: latest

    - name: install psmisc
      yum:
        name: psmisc
        state: present

    - name: adjust upd socket buffer
      shell: "sysctl -w net.core.rmem_max=500000000"
