---
- hosts: aws
  become: true

  tasks:
    - name: adjust upd socket buffer
      shell: "sysctl -w net.core.rmem_max=500000000"

    - name: copy msend
      copy:
        src: /home/chriswang/Desktop/customer-connect/ansible/msend
        dest: /usr/bin/msend
        mode: "777"
    - name: copy mreceive
      copy:
        src: /home/chriswang/Desktop/customer-connect/ansible/mreceive
        dest: /usr/bin/mreceive
        mode: "777"
    - name: copy tmreceive
      copy:
        src: /home/chriswang/Desktop/customer-connect/tmreceive
        dest: /usr/bin/tmreceive
        mode: "777"

    - name: copy tmsend
      copy:
        src: /home/chriswang/Desktop/customer-connect/tmsend
        dest: /usr/bin/tmsend
        mode: "777"

    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: install rpms
      yum:
        name:
          - openvpn
          - zip
          - unzip
          - ntpdate
        state: present

    - name: copy files
      copy:
        src: /home/chriswang/Desktop/customer-connect/openvpn/{{ item.name}}
        dest: /etc/openvpn/{{ item.name}}
        mode: "644"
      loop:
        - { name: "ca.crt" }
        - { name: "dh2048.pem" }
        - { name: "server.conf" }
        - { name: "server.crt" }
        - { name: "server.key" }

    - name: copy files
      copy:
        src: /home/chriswang/Desktop/customer-connect/openvpn/{{ item.name}}
        dest: /etc/pam.d/{{ item.name}}
        mode: "644"
      loop:
        - { name: "openvpn" }

    # - name: Enable password login
    #   lineinfile:
    #     path: /etc/ssh/sshd_config
    #     regexp: "^PasswordAuthentication"
    #     line: PasswordAuthentication yes

    - name: Ensure ipforward
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "^net.ipv4.ip_forward"
        line: net.ipv4.ip_forward=1

    - name: enable sysctl
      shell: "sysctl -p"

    - name: Creates  openvpnclient directory
      file:
        path: /root/openvpnclient
        state: directory

    - name: copy
      copy:
        src: /home/chriswang/Desktop/customer-connect/openvpn/opvclient.zip
        dest: /root/openvpnclient/opvclient.zip
        mode: "777"

    - name: copy client file
      copy:
        src: /home/chriswang/Desktop/customer-connect/openvpn/{{ item.name }}
        dest: /root/openvpnclient/{{ item.name }}
      loop:
        - { name: "client.ovpn" }
        - { name: "login.conf" }
        - { name: "ca.crt" }

    - name: unzip
      shell: "cd /root/openvpnclient && unzip opvclient.zip"
